baseurl: ""
url: "https://kodedevel.ir"
logo: "/resources/image/favicon.png"

social:
  name: "KodeDevel"
  links:
    - "https://t.me/KodeDevel"
    - "https://t.me/KodeDevel_Chat"
    - "https://github.io/KodeDevel"

author:
  name: "یونس سلیمانی"
  email: "soleimani.yunes@gmail.com"
  telegram: "https://t.me/skybirdbits"


